-- MySQL Script generated by MySQL Workbench
-- Fri May  1 13:48:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`priority` (
  `idpriority` INT(11) NOT NULL AUTO_INCREMENT,
  `priority` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpriority`),
  UNIQUE INDEX `priority_UNIQUE` (`priority` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `idrole` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrole`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `role` INT(11) NULL DEFAULT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `assign_project` INT(11) NULL DEFAULT NULL,
  `login` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC),
  INDEX `role_idx` (`role` ASC),
  INDEX `fk_project_idx` (`assign_project` ASC),
  CONSTRAINT `fk_assign_project`
    FOREIGN KEY (`assign_project`)
    REFERENCES `mydb`.`project` (`idproject`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_role`
    FOREIGN KEY (`role`)
    REFERENCES `mydb`.`role` (`idrole`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `idproject` INT(11) NOT NULL AUTO_INCREMENT,
  `project_code` VARCHAR(45) NOT NULL,
  `project_name` VARCHAR(45) NOT NULL,
  `project_creator` INT(11) NOT NULL,
  `date_of_completion` DATE NOT NULL,
  `readiness_degree` DOUBLE NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idproject`),
  UNIQUE INDEX `project_code_UNIQUE` (`project_code` ASC),
  INDEX `fk_user_idx` (`project_creator` ASC),
  CONSTRAINT `fk_project_creator`
    FOREIGN KEY (`project_creator`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `idstatus` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`task` (
  `idtask` INT(11) NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(45) NOT NULL,
  `date_of_creation` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `task_code` VARCHAR(45) NOT NULL,
  `status` INT(11) NOT NULL,
  `priority` INT(11) NOT NULL,
  `task_creator` INT(11) NOT NULL,
  `task_executor` INT(11) NULL DEFAULT NULL,
  `project` INT(11) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idtask`),
  UNIQUE INDEX `task_code_UNIQUE` (`task_code` ASC),
  INDEX `fk_priority_idx` (`priority` ASC),
  INDEX `fk_status_idx` (`status` ASC),
  INDEX `fk_project_idx` (`project` ASC),
  INDEX `fk_executor_idx` (`task_executor` ASC),
  INDEX `fk_creator_idx` (`task_creator` ASC),
  CONSTRAINT `fk_priority`
    FOREIGN KEY (`priority`)
    REFERENCES `mydb`.`priority` (`idpriority`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_project`
    FOREIGN KEY (`project`)
    REFERENCES `mydb`.`project` (`idproject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_status`
    FOREIGN KEY (`status`)
    REFERENCES `mydb`.`status` (`idstatus`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_creator`
    FOREIGN KEY (`task_creator`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_executor`
    FOREIGN KEY (`task_executor`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `idcomment` INT(11) NOT NULL AUTO_INCREMENT,
  `task` INT(11) NULL DEFAULT NULL,
  `comment` TEXT NOT NULL,
  `time_of_creation` DATETIME NOT NULL,
  `user` INT(11) NOT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_task_idx` (`task` ASC),
  INDEX `fk_user_idx` (`user` ASC),
  CONSTRAINT `fk_task`
    FOREIGN KEY (`task`)
    REFERENCES `mydb`.`task` (`idtask`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- insert into user(role,user_name,user_surname,email,assign_project,login,password) values (1,'Oleg','Gorin','gor@mail.com',null,'qwe123','qwe123');
-- insert into user(role,user_name,user_surname,email,assign_project,login,password) values (2,'Vasya','Bolin','gor@mail.com',null,'qwe321','qwe321');
-- insert into user(role,user_name,user_surname,email,assign_project,login,password) values (3,'Oleg','Fomin','gor@mail.com',null,'qwe111','qwe111');
-- insert into user(role,user_name,user_surname,email,assign_project,login,password) values (4,'Kolleg','Holin','gor@mail.com',null,'qwe333','qwe333');

-- insert into status(status) values('open');
-- insert into status(status) values('in progress');
-- insert into status(status) values('ready for test');
-- insert into status(status) values('closed');


-- insert into priority(priority) values('min');
-- insert into priority(priority) values('max');
-- insert into priority(priority) values('middle');


